Ex 127 [M2] Create Orders from Leads: Post-Purchase
helloextend/magento-extension pull request #147
Opened 2022-03-29 15:02 UTC by evgenyukho

2022-03-31 18:42 UTC, sagaydakam requested changes
See comments for the [frontend/layout/cms_index_index.xml]

2022-03-31 18:42 UTC, sagaydakam commented on view/frontend/layout/cms_index_index.xml
> +</page>
1. Why Homepage layout should be changed? At least I didn't find any mention of this page in the requirements
2. In case Homepage should be changed - "postPurchaseLeadWarranty" js-widget requires `extendSdk` which is not included into this layout update (see `<update handle="extend_warranty_installation" />`)

2022-04-01 11:18 UTC, evgenyukho commented on view/frontend/layout/cms_index_index.xml
> +</page>
@sagaydakam @ahofstetter 
1. The homepage layout has been changed for having the opportunity to handle a base URL link with a leadToken in the parameters to enable functionality that shows a modal window with guarantees and the addition of a guarantee to the cart.
2. I haven't connected the extend_warranty_installation handle to the homepage layout, because it is loaded on all pages. That happens because the layout checkout_cart_sidebar_item_renderers handle is included in the default.xml in the Magento_Checkout module. There is <update handle="extend_warranty_installation" /> in this layout. Perhaps this needs to be fixed. Is the current extend_warranty_installation connection correct?

2022-04-01 19:04 UTC, sagaydakam commented on view/frontend/layout/cms_index_index.xml
> +</page>
@evgenyukho 
1. Thank you for details, now it makes sense
2. Would be better to change layout updates logic a little:
- `checkout_cart_sidebar_item_renderers` - apply "extend_warranty_installation" (basically "extend.warranty.js" block) only if Mini-cart is enabled
- `cms_index_index` - apply "extend_warranty_installation" and init "post_purchase_lead_token" block only if "Post Purchase Leads Modal" config is enabled
In this case we will not load extendSdk on those pages where it's not necessary

2022-04-11 11:06 UTC, ahofstetter commented on Plugin/Quote/Item/ItemDataPlugin.php
> +declare(strict_types=1);
Please remove. We don't want to use this in any files in the extension since it can cause merchants issues when types are incorrect.

2022-04-11 11:06 UTC, ahofstetter commented on Plugin/Quote/Model/Item/SetItemDataPlugin.php
> +declare(strict_types=1);
Please remove

2022-04-11 15:50 UTC, merged